# Generated by Django 3.2.16 on 2023-07-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20230704_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='field_a',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='field_b',
            field=models.CharField(default='', max_length=100),
        ),
    ]
